export const UrlRoutes = {
  login: "/login",
  dashboard: "/dashboard",
  baseInfoManagement: "/base-info-management",
  customers: "/customers",
  groupCustomerRegistration: "/group-customer-registration",
  paymentMethod: "/payment-method",
  walletManagement: "/wallet-management",
  personalWallet: "/personal-wallet",
  groupWalletIssuance: "/group-wallet-issuance",
  organizationalCardCharge: "/organizational-card-charge",
  walletGroup: "/wallet-group",
  reports: "/reports",
  reportsCard: "/card",
  reportsCardEvents: "/card-events",
  reportsBusinessDeposit: "/business-deposit",
  reportsSettlement: "/settlement",
};
